// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/model/pb/proto/broker.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BrokerState int32

const (
	BrokerState_BOffline  BrokerState = 0
	BrokerState_BOnline   BrokerState = 1
	BrokerState_BWorking  BrokerState = 2
	BrokerState_BAbnormal BrokerState = 3
)

var BrokerState_name = map[int32]string{
	0: "BOffline",
	1: "BOnline",
	2: "BWorking",
	3: "BAbnormal",
}

var BrokerState_value = map[string]int32{
	"BOffline":  0,
	"BOnline":   1,
	"BWorking":  2,
	"BAbnormal": 3,
}

func (x BrokerState) String() string {
	return proto.EnumName(BrokerState_name, int32(x))
}

func (BrokerState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_007312014bcbd17a, []int{0}
}

type BrokerMeta struct {
	Id                   int32       `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	AdminPort            int64       `protobuf:"varint,2,opt,name=adminPort,proto3" json:"adminPort,omitempty"`
	ServicePort          int64       `protobuf:"varint,3,opt,name=servicePort,proto3" json:"servicePort,omitempty"`
	HostName             string      `protobuf:"bytes,4,opt,name=hostName,proto3" json:"hostName,omitempty"`
	Ip                   string      `protobuf:"bytes,5,opt,name=ip,proto3" json:"ip,omitempty"`
	State                BrokerState `protobuf:"varint,6,opt,name=state,proto3,enum=BrokerState" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *BrokerMeta) Reset()         { *m = BrokerMeta{} }
func (m *BrokerMeta) String() string { return proto.CompactTextString(m) }
func (*BrokerMeta) ProtoMessage()    {}
func (*BrokerMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_007312014bcbd17a, []int{0}
}

func (m *BrokerMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BrokerMeta.Unmarshal(m, b)
}
func (m *BrokerMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BrokerMeta.Marshal(b, m, deterministic)
}
func (m *BrokerMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BrokerMeta.Merge(m, src)
}
func (m *BrokerMeta) XXX_Size() int {
	return xxx_messageInfo_BrokerMeta.Size(m)
}
func (m *BrokerMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_BrokerMeta.DiscardUnknown(m)
}

var xxx_messageInfo_BrokerMeta proto.InternalMessageInfo

func (m *BrokerMeta) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *BrokerMeta) GetAdminPort() int64 {
	if m != nil {
		return m.AdminPort
	}
	return 0
}

func (m *BrokerMeta) GetServicePort() int64 {
	if m != nil {
		return m.ServicePort
	}
	return 0
}

func (m *BrokerMeta) GetHostName() string {
	if m != nil {
		return m.HostName
	}
	return ""
}

func (m *BrokerMeta) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *BrokerMeta) GetState() BrokerState {
	if m != nil {
		return m.State
	}
	return BrokerState_BOffline
}

func init() {
	proto.RegisterEnum("BrokerState", BrokerState_name, BrokerState_value)
	proto.RegisterType((*BrokerMeta)(nil), "BrokerMeta")
}

func init() { proto.RegisterFile("pkg/model/pb/proto/broker.proto", fileDescriptor_007312014bcbd17a) }

var fileDescriptor_007312014bcbd17a = []byte{
	// 235 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0x86, 0x4d, 0x6a, 0xd7, 0xed, 0xb4, 0x96, 0x92, 0x53, 0x10, 0xc1, 0xb0, 0xa7, 0xe2, 0x61,
	0x0b, 0xfa, 0x04, 0x06, 0x3c, 0xea, 0x4a, 0x3d, 0x08, 0xde, 0x52, 0x9b, 0x5d, 0x43, 0xdb, 0x24,
	0xa4, 0xc1, 0xa7, 0xf2, 0x21, 0xc5, 0x29, 0x68, 0x8f, 0xdf, 0xf7, 0x1d, 0x66, 0xf8, 0xe1, 0xc6,
	0x0f, 0xa7, 0x66, 0x72, 0xbd, 0x1e, 0x1b, 0xdf, 0x35, 0x3e, 0xb8, 0xe8, 0x9a, 0x2e, 0xb8, 0x41,
	0x87, 0x3d, 0xc2, 0xee, 0x9b, 0x00, 0x48, 0x14, 0x4f, 0x3a, 0x2a, 0x56, 0x02, 0x35, 0x3d, 0x27,
	0x82, 0xd4, 0x69, 0x4b, 0x4d, 0xcf, 0xae, 0x21, 0x53, 0xfd, 0x64, 0xec, 0x8b, 0x0b, 0x91, 0x53,
	0x41, 0xea, 0xa4, 0xfd, 0x17, 0x4c, 0x40, 0x3e, 0xeb, 0xf0, 0x65, 0x3e, 0x34, 0xf6, 0x04, 0xfb,
	0x5a, 0xb1, 0x2b, 0xd8, 0x7e, 0xba, 0x39, 0x3e, 0xab, 0x49, 0xf3, 0x73, 0x41, 0xea, 0xac, 0xfd,
	0x63, 0xbc, 0xe5, 0x79, 0x8a, 0x96, 0x1a, 0xcf, 0x76, 0x90, 0xce, 0x51, 0x45, 0xcd, 0x37, 0x82,
	0xd4, 0xe5, 0x5d, 0xb1, 0x5f, 0xfe, 0x7a, 0xfd, 0x75, 0xed, 0x92, 0x6e, 0x1f, 0x21, 0x5f, 0x59,
	0x56, 0xc0, 0x56, 0x1e, 0x8e, 0xc7, 0xd1, 0x58, 0x5d, 0x9d, 0xb1, 0x1c, 0x2e, 0xe4, 0xc1, 0x22,
	0x10, 0x4c, 0x6f, 0x2e, 0x0c, 0xc6, 0x9e, 0x2a, 0xca, 0x2e, 0x21, 0x93, 0x0f, 0x9d, 0x75, 0x61,
	0x52, 0x63, 0x95, 0xc8, 0xf2, 0xbd, 0x58, 0x0f, 0xd3, 0x6d, 0x70, 0x8c, 0xfb, 0x9f, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xf3, 0x8a, 0x2a, 0x48, 0x2f, 0x01, 0x00, 0x00,
}
