// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/model/pb/proto/cluster.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ClusterMeta struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id                   int32    `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClusterMeta) Reset()         { *m = ClusterMeta{} }
func (m *ClusterMeta) String() string { return proto.CompactTextString(m) }
func (*ClusterMeta) ProtoMessage()    {}
func (*ClusterMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_a927964afda86f78, []int{0}
}

func (m *ClusterMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClusterMeta.Unmarshal(m, b)
}
func (m *ClusterMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClusterMeta.Marshal(b, m, deterministic)
}
func (m *ClusterMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClusterMeta.Merge(m, src)
}
func (m *ClusterMeta) XXX_Size() int {
	return xxx_messageInfo_ClusterMeta.Size(m)
}
func (m *ClusterMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_ClusterMeta.DiscardUnknown(m)
}

var xxx_messageInfo_ClusterMeta proto.InternalMessageInfo

func (m *ClusterMeta) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ClusterMeta) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto.RegisterType((*ClusterMeta)(nil), "ClusterMeta")
}

func init() { proto.RegisterFile("pkg/model/pb/proto/cluster.proto", fileDescriptor_a927964afda86f78) }

var fileDescriptor_a927964afda86f78 = []byte{
	// 110 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x28, 0xc8, 0x4e, 0xd7,
	0xcf, 0xcd, 0x4f, 0x49, 0xcd, 0xd1, 0x2f, 0x48, 0xd2, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0xd7, 0x4f,
	0xce, 0x29, 0x2d, 0x2e, 0x49, 0x2d, 0xd2, 0x03, 0xf3, 0x94, 0x0c, 0xb9, 0xb8, 0x9d, 0x21, 0x02,
	0xbe, 0xa9, 0x25, 0x89, 0x42, 0x42, 0x5c, 0x2c, 0x79, 0x89, 0xb9, 0xa9, 0x12, 0x8c, 0x0a, 0x8c,
	0x1a, 0x9c, 0x41, 0x60, 0xb6, 0x10, 0x1f, 0x17, 0x53, 0x66, 0x8a, 0x04, 0x93, 0x02, 0xa3, 0x06,
	0x6b, 0x10, 0x53, 0x66, 0x8a, 0x13, 0x5f, 0x14, 0x0f, 0xb2, 0xb1, 0x49, 0x6c, 0x60, 0x93, 0x8c,
	0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0xe5, 0x47, 0x9e, 0x12, 0x6d, 0x00, 0x00, 0x00,
}
