// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/model/pb/proto/consumer.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ConsumeType int32

const (
	ConsumeType_Pull ConsumeType = 0
	ConsumeType_Push ConsumeType = 1
)

var ConsumeType_name = map[int32]string{
	0: "Pull",
	1: "Push",
}

var ConsumeType_value = map[string]int32{
	"Pull": 0,
	"Push": 1,
}

func (x ConsumeType) String() string {
	return proto.EnumName(ConsumeType_name, int32(x))
}

func (ConsumeType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_89c4baf93f5bc8b5, []int{0}
}

type ConsumeMode int32

const (
	ConsumeMode_Exclusive ConsumeMode = 0
	ConsumeMode_Shared    ConsumeMode = 1
	ConsumeMode_StandBy   ConsumeMode = 2
)

var ConsumeMode_name = map[int32]string{
	0: "Exclusive",
	1: "Shared",
	2: "StandBy",
}

var ConsumeMode_value = map[string]int32{
	"Exclusive": 0,
	"Shared":    1,
	"StandBy":   2,
}

func (x ConsumeMode) String() string {
	return proto.EnumName(ConsumeMode_name, int32(x))
}

func (ConsumeMode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_89c4baf93f5bc8b5, []int{1}
}

type ConsumeState int32

const (
	ConsumeState_COffline     ConsumeState = 0
	ConsumeState_COnline      ConsumeState = 1
	ConsumeState_CRebalancing ConsumeState = 2
	ConsumeState_CConsuming   ConsumeState = 3
)

var ConsumeState_name = map[int32]string{
	0: "COffline",
	1: "COnline",
	2: "CRebalancing",
	3: "CConsuming",
}

var ConsumeState_value = map[string]int32{
	"COffline":     0,
	"COnline":      1,
	"CRebalancing": 2,
	"CConsuming":   3,
}

func (x ConsumeState) String() string {
	return proto.EnumName(ConsumeState_name, int32(x))
}

func (ConsumeState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_89c4baf93f5bc8b5, []int{2}
}

type ConsumerMeta struct {
	Name                 string       `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id                   int32        `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Topics               []int32      `protobuf:"varint,3,rep,packed,name=topics,proto3" json:"topics,omitempty"`
	SubscribedOwner      int32        `protobuf:"varint,4,opt,name=subscribedOwner,proto3" json:"subscribedOwner,omitempty"`
	SubscribedNamespace  int32        `protobuf:"varint,5,opt,name=subscribedNamespace,proto3" json:"subscribedNamespace,omitempty"`
	Type                 ConsumeType  `protobuf:"varint,6,opt,name=type,proto3,enum=ConsumeType" json:"type,omitempty"`
	Mode                 ConsumeMode  `protobuf:"varint,7,opt,name=mode,proto3,enum=ConsumeMode" json:"mode,omitempty"`
	State                ConsumeState `protobuf:"varint,8,opt,name=state,proto3,enum=ConsumeState" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ConsumerMeta) Reset()         { *m = ConsumerMeta{} }
func (m *ConsumerMeta) String() string { return proto.CompactTextString(m) }
func (*ConsumerMeta) ProtoMessage()    {}
func (*ConsumerMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_89c4baf93f5bc8b5, []int{0}
}

func (m *ConsumerMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConsumerMeta.Unmarshal(m, b)
}
func (m *ConsumerMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConsumerMeta.Marshal(b, m, deterministic)
}
func (m *ConsumerMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConsumerMeta.Merge(m, src)
}
func (m *ConsumerMeta) XXX_Size() int {
	return xxx_messageInfo_ConsumerMeta.Size(m)
}
func (m *ConsumerMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_ConsumerMeta.DiscardUnknown(m)
}

var xxx_messageInfo_ConsumerMeta proto.InternalMessageInfo

func (m *ConsumerMeta) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ConsumerMeta) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ConsumerMeta) GetTopics() []int32 {
	if m != nil {
		return m.Topics
	}
	return nil
}

func (m *ConsumerMeta) GetSubscribedOwner() int32 {
	if m != nil {
		return m.SubscribedOwner
	}
	return 0
}

func (m *ConsumerMeta) GetSubscribedNamespace() int32 {
	if m != nil {
		return m.SubscribedNamespace
	}
	return 0
}

func (m *ConsumerMeta) GetType() ConsumeType {
	if m != nil {
		return m.Type
	}
	return ConsumeType_Pull
}

func (m *ConsumerMeta) GetMode() ConsumeMode {
	if m != nil {
		return m.Mode
	}
	return ConsumeMode_Exclusive
}

func (m *ConsumerMeta) GetState() ConsumeState {
	if m != nil {
		return m.State
	}
	return ConsumeState_COffline
}

func init() {
	proto.RegisterEnum("ConsumeType", ConsumeType_name, ConsumeType_value)
	proto.RegisterEnum("ConsumeMode", ConsumeMode_name, ConsumeMode_value)
	proto.RegisterEnum("ConsumeState", ConsumeState_name, ConsumeState_value)
	proto.RegisterType((*ConsumerMeta)(nil), "ConsumerMeta")
}

func init() { proto.RegisterFile("pkg/model/pb/proto/consumer.proto", fileDescriptor_89c4baf93f5bc8b5) }

var fileDescriptor_89c4baf93f5bc8b5 = []byte{
	// 338 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xcf, 0x4e, 0xab, 0x50,
	0x10, 0xc6, 0x0b, 0x05, 0xda, 0x4e, 0x29, 0x97, 0xcc, 0x4d, 0x6e, 0xce, 0x92, 0x5e, 0x37, 0xa4,
	0x8b, 0x62, 0x34, 0xbe, 0x40, 0x89, 0x2b, 0x53, 0x6b, 0xa8, 0x2b, 0x77, 0x07, 0x98, 0xb6, 0x44,
	0x38, 0x10, 0x0e, 0xa8, 0x7d, 0x0a, 0x5f, 0xd9, 0x70, 0x5a, 0x6b, 0x35, 0xee, 0xe6, 0xfb, 0xbe,
	0xdf, 0xcc, 0xf9, 0x33, 0x30, 0xad, 0x9e, 0xb7, 0x41, 0x51, 0xa6, 0x94, 0x07, 0x55, 0x1c, 0x54,
	0x75, 0xd9, 0x94, 0x41, 0x52, 0x0a, 0xd9, 0x16, 0x54, 0xcf, 0x95, 0xfc, 0xff, 0xae, 0x83, 0x1d,
	0x1e, 0xad, 0x25, 0x35, 0x1c, 0x11, 0x0c, 0xc1, 0x0b, 0x62, 0x9a, 0xa7, 0xf9, 0xa3, 0x48, 0xd5,
	0xe8, 0x80, 0x9e, 0xa5, 0x4c, 0xf7, 0x34, 0xdf, 0x8c, 0xf4, 0x2c, 0xc5, 0x7f, 0x60, 0x35, 0x65,
	0x95, 0x25, 0x92, 0xf5, 0xbd, 0xbe, 0x6f, 0x46, 0x47, 0x85, 0x3e, 0xfc, 0x91, 0x6d, 0x2c, 0x93,
	0x3a, 0x8b, 0x29, 0x5d, 0xbd, 0x0a, 0xaa, 0x99, 0xa1, 0x9a, 0x7e, 0xda, 0x78, 0x09, 0x7f, 0xbf,
	0xac, 0x7b, 0x5e, 0x90, 0xac, 0x78, 0x42, 0xcc, 0x54, 0xf4, 0x6f, 0x11, 0x7a, 0x60, 0x34, 0xfb,
	0x8a, 0x98, 0xe5, 0x69, 0xbe, 0x73, 0x65, 0xcf, 0x8f, 0x97, 0x7e, 0xdc, 0x57, 0x14, 0xa9, 0xa4,
	0x23, 0xba, 0xb7, 0xb2, 0xc1, 0x77, 0x62, 0x59, 0xa6, 0x14, 0xa9, 0x04, 0x2f, 0xc0, 0x94, 0x0d,
	0x6f, 0x88, 0x0d, 0x15, 0x32, 0xf9, 0x44, 0xd6, 0x9d, 0x19, 0x1d, 0xb2, 0xd9, 0x14, 0xc6, 0x67,
	0xb3, 0x71, 0x08, 0xc6, 0x43, 0x9b, 0xe7, 0x6e, 0xef, 0x50, 0xc9, 0x9d, 0xab, 0xcd, 0x6e, 0x4e,
	0x48, 0x37, 0x1c, 0x27, 0x30, 0xba, 0x7d, 0x4b, 0xf2, 0x56, 0x66, 0x2f, 0xe4, 0xf6, 0x10, 0xc0,
	0x5a, 0xef, 0x78, 0x4d, 0xa9, 0xab, 0xe1, 0x18, 0x06, 0xeb, 0x86, 0x8b, 0x74, 0xb1, 0x77, 0xf5,
	0xd9, 0xdd, 0xe9, 0xab, 0xd5, 0x81, 0x68, 0xc3, 0x30, 0x5c, 0x6d, 0x36, 0x79, 0x26, 0xba, 0xb6,
	0x31, 0x0c, 0xc2, 0x95, 0x50, 0x42, 0x43, 0x17, 0xec, 0x30, 0xa2, 0x98, 0xe7, 0x5c, 0x24, 0x99,
	0xd8, 0xba, 0x3a, 0x3a, 0x00, 0xe1, 0xa1, 0xbb, 0xd3, 0xfd, 0x85, 0xf3, 0x64, 0x9f, 0x6f, 0x37,
	0xb6, 0xd4, 0x3e, 0xaf, 0x3f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x05, 0xce, 0xaa, 0x82, 0xf4, 0x01,
	0x00, 0x00,
}
