// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/model/pb/proto/message.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Message struct {
	Topic                string       `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Partition            int32        `protobuf:"varint,2,opt,name=partition,proto3" json:"partition,omitempty"`
	Offset               int64        `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	Body                 []byte       `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	Meta                 *MessageMeta `protobuf:"bytes,5,opt,name=meta,proto3" json:"meta,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a2716b6d3c088dc, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *Message) GetPartition() int32 {
	if m != nil {
		return m.Partition
	}
	return 0
}

func (m *Message) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *Message) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *Message) GetMeta() *MessageMeta {
	if m != nil {
		return m.Meta
	}
	return nil
}

type MessageMeta struct {
	Key                  []byte            `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	ProducerName         string            `protobuf:"bytes,2,opt,name=producerName,proto3" json:"producerName,omitempty"`
	ProduceSeqID         int64             `protobuf:"varint,3,opt,name=produceSeqID,proto3" json:"produceSeqID,omitempty"`
	Timestamp            int64             `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ReplicatedSrc        []byte            `protobuf:"bytes,5,opt,name=replicatedSrc,proto3" json:"replicatedSrc,omitempty"`
	Properties           map[string]string `protobuf:"bytes,6,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *MessageMeta) Reset()         { *m = MessageMeta{} }
func (m *MessageMeta) String() string { return proto.CompactTextString(m) }
func (*MessageMeta) ProtoMessage()    {}
func (*MessageMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a2716b6d3c088dc, []int{1}
}

func (m *MessageMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageMeta.Unmarshal(m, b)
}
func (m *MessageMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageMeta.Marshal(b, m, deterministic)
}
func (m *MessageMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageMeta.Merge(m, src)
}
func (m *MessageMeta) XXX_Size() int {
	return xxx_messageInfo_MessageMeta.Size(m)
}
func (m *MessageMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageMeta.DiscardUnknown(m)
}

var xxx_messageInfo_MessageMeta proto.InternalMessageInfo

func (m *MessageMeta) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *MessageMeta) GetProducerName() string {
	if m != nil {
		return m.ProducerName
	}
	return ""
}

func (m *MessageMeta) GetProduceSeqID() int64 {
	if m != nil {
		return m.ProduceSeqID
	}
	return 0
}

func (m *MessageMeta) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *MessageMeta) GetReplicatedSrc() []byte {
	if m != nil {
		return m.ReplicatedSrc
	}
	return nil
}

func (m *MessageMeta) GetProperties() map[string]string {
	if m != nil {
		return m.Properties
	}
	return nil
}

func init() {
	proto.RegisterType((*Message)(nil), "Message")
	proto.RegisterType((*MessageMeta)(nil), "MessageMeta")
	proto.RegisterMapType((map[string]string)(nil), "MessageMeta.PropertiesEntry")
}

func init() { proto.RegisterFile("pkg/model/pb/proto/message.proto", fileDescriptor_6a2716b6d3c088dc) }

var fileDescriptor_6a2716b6d3c088dc = []byte{
	// 313 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x91, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0xd9, 0xa6, 0xa9, 0x64, 0x1a, 0xff, 0xb0, 0x14, 0x09, 0xd2, 0xc3, 0x52, 0x3c, 0xe4,
	0xd4, 0x40, 0xbd, 0x88, 0xe8, 0x45, 0xf4, 0xe0, 0xa1, 0x22, 0xdb, 0x9b, 0xb7, 0x6d, 0x32, 0x2d,
	0xa1, 0x4d, 0x77, 0xdd, 0x4c, 0x85, 0x7e, 0x06, 0xbf, 0x88, 0x1f, 0x53, 0xba, 0xa9, 0x76, 0xe3,
	0x6d, 0xde, 0xef, 0x0d, 0xcc, 0x7b, 0x0c, 0x08, 0xb3, 0x5a, 0x66, 0x95, 0x2e, 0x70, 0x9d, 0x99,
	0x79, 0x66, 0xac, 0x26, 0x9d, 0x55, 0x58, 0xd7, 0x6a, 0x89, 0x63, 0xa7, 0x46, 0x5f, 0x0c, 0x4e,
	0xa6, 0x0d, 0xe1, 0x03, 0x08, 0x49, 0x9b, 0x32, 0x4f, 0x98, 0x60, 0x69, 0x24, 0x1b, 0xc1, 0x87,
	0x10, 0x19, 0x65, 0xa9, 0xa4, 0x52, 0x6f, 0x92, 0x8e, 0x60, 0x69, 0x28, 0x8f, 0x80, 0x5f, 0x42,
	0x4f, 0x2f, 0x16, 0x35, 0x52, 0x12, 0x08, 0x96, 0x06, 0xf2, 0xa0, 0x38, 0x87, 0xee, 0x5c, 0x17,
	0xbb, 0xa4, 0x2b, 0x58, 0x1a, 0x4b, 0x37, 0x73, 0x01, 0xdd, 0x0a, 0x49, 0x25, 0xa1, 0x60, 0x69,
	0x7f, 0x12, 0x8f, 0x0f, 0x77, 0xa7, 0x48, 0x4a, 0x3a, 0x67, 0xf4, 0xdd, 0x81, 0xbe, 0x47, 0xf9,
	0x05, 0x04, 0x2b, 0xdc, 0xb9, 0x3c, 0xb1, 0xdc, 0x8f, 0x7c, 0x04, 0xb1, 0xb1, 0xba, 0xd8, 0xe6,
	0x68, 0x5f, 0x55, 0x85, 0x2e, 0x50, 0x24, 0x5b, 0xcc, 0xdb, 0x99, 0xe1, 0xc7, 0xcb, 0xd3, 0x21,
	0x59, 0x8b, 0xed, 0x5b, 0x51, 0x59, 0x61, 0x4d, 0xaa, 0x32, 0x2e, 0x64, 0x20, 0x8f, 0x80, 0x5f,
	0xc3, 0xa9, 0x45, 0xb3, 0x2e, 0x73, 0x45, 0x58, 0xcc, 0x6c, 0xee, 0x22, 0xc7, 0xb2, 0x0d, 0xf9,
	0x3d, 0x80, 0xb1, 0xda, 0xa0, 0xa5, 0x12, 0xeb, 0xa4, 0x27, 0x82, 0xb4, 0x3f, 0x19, 0xfa, 0xad,
	0xc6, 0x6f, 0x7f, 0xf6, 0xf3, 0x86, 0xec, 0x4e, 0x7a, 0xfb, 0x57, 0x0f, 0x70, 0xfe, 0xcf, 0xf6,
	0xeb, 0x46, 0x4d, 0xdd, 0x01, 0x84, 0x9f, 0x6a, 0xbd, 0xfd, 0xed, 0xd9, 0x88, 0xbb, 0xce, 0x2d,
	0x7b, 0x3c, 0x7b, 0x8f, 0xfd, 0xe7, 0xce, 0x7b, 0xee, 0x9f, 0x37, 0x3f, 0x01, 0x00, 0x00, 0xff,
	0xff, 0x78, 0x2f, 0xeb, 0x86, 0xf3, 0x01, 0x00, 0x00,
}
