// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/model/pb/proto/topic.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TopicType int32

const (
	TopicType_Ordered TopicType = 0
	TopicType_Delay   TopicType = 1
)

var TopicType_name = map[int32]string{
	0: "Ordered",
	1: "Delay",
}

var TopicType_value = map[string]int32{
	"Ordered": 0,
	"Delay":   1,
}

func (x TopicType) String() string {
	return proto.EnumName(TopicType_name, int32(x))
}

func (TopicType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0b0b9aeda2f3027a, []int{0}
}

type TopicMeta struct {
	Name                 string    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type                 TopicType `protobuf:"varint,2,opt,name=type,proto3,enum=TopicType" json:"type,omitempty"`
	Id                   int32     `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	PartitionNum         int32     `protobuf:"varint,4,opt,name=partitionNum,proto3" json:"partitionNum,omitempty"`
	Owner                string    `protobuf:"bytes,5,opt,name=owner,proto3" json:"owner,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *TopicMeta) Reset()         { *m = TopicMeta{} }
func (m *TopicMeta) String() string { return proto.CompactTextString(m) }
func (*TopicMeta) ProtoMessage()    {}
func (*TopicMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b0b9aeda2f3027a, []int{0}
}

func (m *TopicMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TopicMeta.Unmarshal(m, b)
}
func (m *TopicMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TopicMeta.Marshal(b, m, deterministic)
}
func (m *TopicMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TopicMeta.Merge(m, src)
}
func (m *TopicMeta) XXX_Size() int {
	return xxx_messageInfo_TopicMeta.Size(m)
}
func (m *TopicMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_TopicMeta.DiscardUnknown(m)
}

var xxx_messageInfo_TopicMeta proto.InternalMessageInfo

func (m *TopicMeta) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TopicMeta) GetType() TopicType {
	if m != nil {
		return m.Type
	}
	return TopicType_Ordered
}

func (m *TopicMeta) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *TopicMeta) GetPartitionNum() int32 {
	if m != nil {
		return m.PartitionNum
	}
	return 0
}

func (m *TopicMeta) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func init() {
	proto.RegisterEnum("TopicType", TopicType_name, TopicType_value)
	proto.RegisterType((*TopicMeta)(nil), "TopicMeta")
}

func init() { proto.RegisterFile("pkg/model/pb/proto/topic.proto", fileDescriptor_0b0b9aeda2f3027a) }

var fileDescriptor_0b0b9aeda2f3027a = []byte{
	// 202 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2b, 0xc8, 0x4e, 0xd7,
	0xcf, 0xcd, 0x4f, 0x49, 0xcd, 0xd1, 0x2f, 0x48, 0xd2, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0xd7, 0x2f,
	0xc9, 0x2f, 0xc8, 0x4c, 0xd6, 0x03, 0xb3, 0x95, 0x3a, 0x19, 0xb9, 0x38, 0x43, 0x40, 0x7c, 0xdf,
	0xd4, 0x92, 0x44, 0x21, 0x21, 0x2e, 0x96, 0xbc, 0xc4, 0xdc, 0x54, 0x09, 0x46, 0x05, 0x46, 0x0d,
	0xce, 0x20, 0x30, 0x5b, 0x48, 0x8e, 0x8b, 0xa5, 0xa4, 0xb2, 0x20, 0x55, 0x82, 0x49, 0x81, 0x51,
	0x83, 0xcf, 0x88, 0x4b, 0x0f, 0xac, 0x3a, 0xa4, 0xb2, 0x20, 0x35, 0x08, 0x2c, 0x2e, 0xc4, 0xc7,
	0xc5, 0x94, 0x99, 0x22, 0xc1, 0xac, 0xc0, 0xa8, 0xc1, 0x1a, 0xc4, 0x94, 0x99, 0x22, 0xa4, 0xc4,
	0xc5, 0x53, 0x90, 0x58, 0x54, 0x92, 0x59, 0x92, 0x99, 0x9f, 0xe7, 0x57, 0x9a, 0x2b, 0xc1, 0x02,
	0x96, 0x41, 0x11, 0x13, 0x12, 0xe1, 0x62, 0xcd, 0x2f, 0xcf, 0x4b, 0x2d, 0x92, 0x60, 0x05, 0x5b,
	0x04, 0xe1, 0x68, 0x29, 0x43, 0x9d, 0x02, 0x32, 0x5c, 0x88, 0x9b, 0x8b, 0xdd, 0xbf, 0x28, 0x25,
	0xb5, 0x28, 0x35, 0x45, 0x80, 0x41, 0x88, 0x93, 0x8b, 0xd5, 0x25, 0x35, 0x27, 0xb1, 0x52, 0x80,
	0xd1, 0x89, 0x2f, 0x8a, 0x07, 0xd9, 0x4b, 0x49, 0x6c, 0x60, 0x7f, 0x18, 0x03, 0x02, 0x00, 0x00,
	0xff, 0xff, 0x77, 0xba, 0x79, 0x12, 0xe9, 0x00, 0x00, 0x00,
}
