// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/model/pb/proto/xq.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type JoinClusterRequest struct {
	Meta                 *BrokerMeta `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *JoinClusterRequest) Reset()         { *m = JoinClusterRequest{} }
func (m *JoinClusterRequest) String() string { return proto.CompactTextString(m) }
func (*JoinClusterRequest) ProtoMessage()    {}
func (*JoinClusterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_418d71c0e6d9a864, []int{0}
}

func (m *JoinClusterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinClusterRequest.Unmarshal(m, b)
}
func (m *JoinClusterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinClusterRequest.Marshal(b, m, deterministic)
}
func (m *JoinClusterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinClusterRequest.Merge(m, src)
}
func (m *JoinClusterRequest) XXX_Size() int {
	return xxx_messageInfo_JoinClusterRequest.Size(m)
}
func (m *JoinClusterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinClusterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_JoinClusterRequest proto.InternalMessageInfo

func (m *JoinClusterRequest) GetMeta() *BrokerMeta {
	if m != nil {
		return m.Meta
	}
	return nil
}

type JoinClusterReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinClusterReply) Reset()         { *m = JoinClusterReply{} }
func (m *JoinClusterReply) String() string { return proto.CompactTextString(m) }
func (*JoinClusterReply) ProtoMessage()    {}
func (*JoinClusterReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_418d71c0e6d9a864, []int{1}
}

func (m *JoinClusterReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinClusterReply.Unmarshal(m, b)
}
func (m *JoinClusterReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinClusterReply.Marshal(b, m, deterministic)
}
func (m *JoinClusterReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinClusterReply.Merge(m, src)
}
func (m *JoinClusterReply) XXX_Size() int {
	return xxx_messageInfo_JoinClusterReply.Size(m)
}
func (m *JoinClusterReply) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinClusterReply.DiscardUnknown(m)
}

var xxx_messageInfo_JoinClusterReply proto.InternalMessageInfo

func init() {
	proto.RegisterType((*JoinClusterRequest)(nil), "JoinClusterRequest")
	proto.RegisterType((*JoinClusterReply)(nil), "JoinClusterReply")
}

func init() { proto.RegisterFile("pkg/model/pb/proto/xq.proto", fileDescriptor_418d71c0e6d9a864) }

var fileDescriptor_418d71c0e6d9a864 = []byte{
	// 154 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2e, 0xc8, 0x4e, 0xd7,
	0xcf, 0xcd, 0x4f, 0x49, 0xcd, 0xd1, 0x2f, 0x48, 0xd2, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0xd7, 0xaf,
	0x28, 0xd4, 0x03, 0x33, 0xa4, 0xe4, 0xb1, 0x48, 0x26, 0x15, 0xe5, 0x67, 0xa7, 0x16, 0x41, 0x14,
	0x28, 0x99, 0x72, 0x09, 0x79, 0xe5, 0x67, 0xe6, 0x39, 0xe7, 0x94, 0x16, 0x97, 0xa4, 0x16, 0x05,
	0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x08, 0xc9, 0x73, 0xb1, 0xe4, 0xa6, 0x96, 0x24, 0x4a, 0x30,
	0x2a, 0x30, 0x6a, 0x70, 0x1b, 0x71, 0xeb, 0x39, 0x81, 0xb5, 0xf8, 0xa6, 0x96, 0x24, 0x06, 0x81,
	0x25, 0x94, 0x84, 0xb8, 0x04, 0x50, 0xb4, 0x15, 0xe4, 0x54, 0x1a, 0x59, 0x73, 0x31, 0x45, 0x04,
	0x0a, 0x99, 0x72, 0x71, 0x23, 0xc9, 0x08, 0x09, 0xeb, 0x61, 0x1a, 0x2f, 0x25, 0xa8, 0x87, 0xae,
	0xd9, 0x89, 0x2f, 0x8a, 0x07, 0xd9, 0xa9, 0x49, 0x6c, 0x60, 0xe7, 0x19, 0x03, 0x02, 0x00, 0x00,
	0xff, 0xff, 0x8e, 0xf8, 0x32, 0x22, 0xde, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// XQClient is the client API for XQ service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type XQClient interface {
	JoinCluster(ctx context.Context, in *JoinClusterRequest, opts ...grpc.CallOption) (*JoinClusterReply, error)
}

type xQClient struct {
	cc *grpc.ClientConn
}

func NewXQClient(cc *grpc.ClientConn) XQClient {
	return &xQClient{cc}
}

func (c *xQClient) JoinCluster(ctx context.Context, in *JoinClusterRequest, opts ...grpc.CallOption) (*JoinClusterReply, error) {
	out := new(JoinClusterReply)
	err := c.cc.Invoke(ctx, "/XQ/JoinCluster", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// XQServer is the server API for XQ service.
type XQServer interface {
	JoinCluster(context.Context, *JoinClusterRequest) (*JoinClusterReply, error)
}

// UnimplementedXQServer can be embedded to have forward compatible implementations.
type UnimplementedXQServer struct {
}

func (*UnimplementedXQServer) JoinCluster(ctx context.Context, req *JoinClusterRequest) (*JoinClusterReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method JoinCluster not implemented")
}

func RegisterXQServer(s *grpc.Server, srv XQServer) {
	s.RegisterService(&_XQ_serviceDesc, srv)
}

func _XQ_JoinCluster_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinClusterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XQServer).JoinCluster(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/XQ/JoinCluster",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XQServer).JoinCluster(ctx, req.(*JoinClusterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _XQ_serviceDesc = grpc.ServiceDesc{
	ServiceName: "XQ",
	HandlerType: (*XQServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "JoinCluster",
			Handler:    _XQ_JoinCluster_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/model/pb/proto/xq.proto",
}
